#!/bin/bash

# Check if the log file exists
if [ ! -f webserver.log ]; then
	    echo "Log file 'webserver.log' not found."
	        exit 1
fi

# Read the log file and extract hosts/IPs
awk '{print $1}' webserver.log | sort | uniq -c | sort -rn | head -n 11
